import { Hono } from "hono";
import { eq, and } from "drizzle-orm";
import { getDb, schema } from "../db/index.js";
import { requireAuth } from "../middleware/auth.js";

export const exportRoutes = new Hono();

exportRoutes.use("*", requireAuth);

/**
 * GET /api/v1/orrs/:orrId/export/markdown
 * Export ORR as structured markdown document.
 */
exportRoutes.get("/markdown", (c) => {
  const user = c.get("user");
  const orrId = c.req.param("orrId")!;
  const db = getDb();

  const orr = db
    .select()
    .from(schema.orrs)
    .where(and(eq(schema.orrs.id, orrId), eq(schema.orrs.teamId, user.teamId)))
    .get();

  if (!orr) {
    return c.json({ error: "not_found", message: "ORR not found" }, 404);
  }

  const sections = db
    .select()
    .from(schema.sections)
    .where(eq(schema.sections.orrId, orrId))
    .all()
    .sort((a, b) => a.position - b.position);

  const team = db
    .select()
    .from(schema.teams)
    .where(eq(schema.teams.id, orr.teamId))
    .get();

  // Build markdown
  const lines: string[] = [];
  lines.push(`# Operational Readiness Review: ${orr.serviceName}`);
  lines.push("");
  lines.push(`**Team:** ${team?.name || "Unknown"}`);
  lines.push(`**Status:** ${orr.status}`);
  lines.push(`**Created:** ${orr.createdAt}`);
  lines.push(`**Last Updated:** ${orr.updatedAt}`);
  if (orr.completedAt) {
    lines.push(`**Completed:** ${orr.completedAt}`);
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  // Coverage summary
  const covered = sections.filter((s) => s.depth !== "UNKNOWN").length;
  lines.push(`## Coverage: ${covered}/${sections.length} sections reviewed`);
  lines.push("");

  for (const section of sections) {
    const depthLabel = {
      UNKNOWN: "Not reviewed",
      SURFACE: "Surface",
      MODERATE: "Moderate",
      DEEP: "Deep",
    }[section.depth] || "Unknown";

    lines.push(`## ${section.position}. ${section.title}`);
    lines.push("");
    lines.push(`**Depth:** ${depthLabel}`);
    if (section.depthRationale) {
      lines.push(`**Assessment:** ${section.depthRationale}`);
    }

    // Flags
    const flags = typeof section.flags === "string"
      ? JSON.parse(section.flags)
      : section.flags;
    if ((flags as Array<{ type: string; note: string }>).length > 0) {
      lines.push("");
      lines.push("**Flags:**");
      for (const f of flags as Array<{ type: string; note: string }>) {
        const icon = { RISK: "⚠️", GAP: "🔴", STRENGTH: "✅", FOLLOW_UP: "📋" }[f.type] || "•";
        lines.push(`- ${icon} **${f.type}:** ${f.note}`);
      }
    }

    // Prompts
    const prompts = typeof section.prompts === "string"
      ? JSON.parse(section.prompts)
      : section.prompts;
    lines.push("");
    lines.push("### Prompts");
    for (const p of prompts as string[]) {
      lines.push(`- ${p}`);
    }

    // Content
    if (section.content) {
      lines.push("");
      lines.push("### Responses & Observations");
      lines.push("");
      lines.push(section.content);
    }

    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push("*Generated by ORR Companion*");

  const markdown = lines.join("\n");

  return new Response(markdown, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="orr-${orr.serviceName.replace(/[^a-zA-Z0-9]/g, "-")}.md"`,
    },
  });
});
